### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by Neve12ende12** [petecoop/laravel-inky#1]
I keep getting the following error when trying to send mail.

 [ErrorException]
  Undefined offset: 1

**Comment by petecoop** [comment]
Hey howcome you closed this? Did you find the cause of the issue?

**Comment by Neve12ende12** [comment]
Because the problem started occurring right after I installed this code, but it turns out that my password has just expired on the SMTP server I was using to test the emails.

By the way, I love this code.  Makes sending emails so easy.  Thank you so much!

**Comment by petecoop** [comment]
Thanks :) Haven't actually had chance to use it yet myself, let me know how you get on!
