### ISSUE TITLE
Class does not inject whole CSS file into <style>

### ISSUE THREAD

**Issue by fsasvari** [petecoop/laravel-inky#2]
In layout I have:

`<link rel="stylesheet" href="foundation-emails.css">`

I expect that class injects whole CSS file between

`<style></style>`

But it only injects part of file.

Inlining is fine, it works well, but injecting does not works like expected.

Is there any solution to this problem ?

**Comment by fsasvari** [comment]
I just run some tests and it looks like the problem is in Emogrifier class. 

**InkyCompilerEngine.php**

`33 -  $emogrifier = new Emogrifier($results, $styles);`

$results and $styles are original from my resources/views/ and resources/assets/css/ files.

Is there any options in emogrifier to keeps original CSS style in head ?

**Comment by fsasvari** [comment]
Found solution, after:

`$emogrifier = new Emogrifier($results, $styles);`

put

`$emogrifier->disableStyleBlocksParsing();`

So, if I manually inject styles in <style> tag it won't inject another styles. If I leave <style> empty it will inject CSS into styles...

Also, good option is to have 

`$emogrifier->enableCssToHtmlMapping();`

For inlining HTML attributes on HTML tag from CSS file.

**Comment by petecoop** [comment]
Hey @fsasvari thanks for taking time to report the issue here, I'm not sure I understand your issue fully, would you be able to share some test code for the issue?

`$emogrifier->disableStyleBlocksParsing();` but we want to parse style blocks don't we? It should inline any styles as generally email clients don't like `<style>` tags.

`$emogrifier->enableCssToHtmlMapping();` I haven't seen this option but looks like something that should be included

**Comment by petecoop** [comment]
Ah I think what you were expecting was that your stylesheet from your `<link>` tag to be put into a `<style>` block?

This isn't the case due to email clients that don't like `<style>` tags e.g. Gmail.

You can see a nice reference to what's supported in email clients here: [CSS Support Guide for Email Clients](https://www.campaignmonitor.com/css/)

**Comment by fsasvari** [comment]
Yes, but why not, Gmail (web) does not support it, but Android app (gmail) supports it from last month - https://www.campaignmonitor.com/blog/email-marketing/2016/09/responsive-email-support-in-gmail-is-coming/

Looks like emogrifier strips some CSS from my `<style>` and then it does not shows well in Android Apps. It also strips some Outloook code like:

```
#outlook a {
  padding: 0;
}

.ExternalClass {
  width: 100%;
}
  .ExternalClass,
  .ExternalClass p,
  .ExternalClass span,
  .ExternalClass font,
  .ExternalClass td,
  .ExternalClass div {
    line-height: 100%;
}
```

All I want is that script leaves `<style>` tag intact or merge CSS file and <style> tag. After that, inlines everything that needs inlining.

**Comment by petecoop** [comment]
if you remove `$emogrifier->disableStyleBlocksParsing();` but put in `$emogrifier->enableCssToHtmlMapping();` does it still not look good in Android?

The whole point of inlining the CSS is that it adds the exact same styles as the `<style>` tags.

I could add a config file to turn certain things on/off as if you're bothered about Gmail (web) then you have to remove the `<style>` tags

**Comment by petecoop** [comment]
Ah I see Gmail has been rolling out `<style>` tag support recently, I don't want to make the default use `<style>` but certainly adding a config option to let you choose

**Comment by fsasvari** [comment]
> The whole point of inlining the CSS is that it adds the exact same styles as the `<style>` tags.

Hmmm, I think this is the problem, with emogrifier. I need original custom `<style>`, but automatic inlining from CSS and/or `<style>`.

I think that Gmail (web) just skips `<style>` tag and goes for inlining. And thats ok, I just need to expand support for Outlook, Gmail (android) etc...

**Comment by fsasvari** [comment]
> Ah I see Gmail has been rolling out `<style>` tag support recently, I don't want to make the default use `<style>` but certainly adding a config option to let you choose

That would be great, thank you!

**Comment by petecoop** [comment]
>I think that Gmail (web) just skips <style> tag and goes for inlining. And thats ok, I just need to expand support for Outlook, Gmail (android) etc...

Yes Gmail web, at least before `<style>` tag support will just strip them out, so you would lose those styles.

I'm just thinking on what is the best combination of options here..

- inline everything
- inject all css into `<style>` tags
- inline external css, leave `<style>` tags as they are

**Comment by petecoop** [comment]
>I think that Gmail (web) just skips <style> tag and goes for inlining. And thats ok, I just need to expand support for Outlook, Gmail (android)

Yes Gmail web, at least before `<style>` tag support will just strip them out, so you would lose those styles.

I'm just thinking on what is the best combination of options here..

- inline everything
- inject all css into `<style>` tags
- inline external css, leave `<style>` tags as they are

**Comment by petecoop** [comment]
no idea what github is doing with my comment there..

**Comment by fsasvari** [comment]
I think that best option is to merge CSS file and CSS inside `<style>` to `<style>` tag and then inline everything that needs inlining, but i dont know if emogrifier has that options.

P.S. need to add "code" formating for `<style>` element

**Comment by petecoop** [comment]
It'd be possible to have all those combinations, I think for now I'll keep current behaviour but add the  `$emogrifier->enableCssToHtmlMapping();` by default. But add a config file to allow you to setup whichever combination works best for you.

**Comment by petecoop** [comment]
I think the config I'll add is:
```
external => 'inline' or 'inject' or 'ignore/false'
inlineStyle => true or false
```

**Comment by fsasvari** [comment]
I think that would be ok ;) thank you very much!

**Comment by fsasvari** [comment]
After additional debugging, it looks like the problem is with [thampe/inky](https://github.com/thampe/inky) package. I don't know where exactly, but somehow it adds addition 2 `<style>` elements.

**Comment by petecoop** [comment]
Oh okay, are you going to open an issue over there?
