### ISSUE TITLE
Support for Laravel 5.4 ?

### ISSUE THREAD

**Issue by fsasvari** [petecoop/laravel-inky#5]
I'm having problems with including this package with Laravel 5.4 when running composer update:

- Conclusion: remove laravel/framework v5.4.1
- Installation request for petecoop/laravel-inky ^0.2.0 -> satisfiable by petecoop/laravel-inky[0.2.0].
 - Conclusion: don't install laravel/framework v5.4.1
 - Conclusion: don't install laravel/framework v5.4.0
 - petecoop/laravel-inky 0.2.0 requires illuminate/view 5.1.*|5.2.*|5.3.* -> satisfiable by laravel/framework[5.3.x-dev], illuminate/view[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
 - Can only install one of: laravel/framework[5.4.x-dev, 5.3.x-dev].

Is there any plans for expanding laravel-inky package to Laravel 5.4 version ?

**Comment by petecoop** [comment]
Yes, hold on 5.4 literally came out yesterday lol

**Comment by fsasvari** [comment]
No time to lose :D

**Comment by petecoop** [comment]
Now supports 5.4, just update to `0.4.0`
